
{{- if contains $.Values.buildScope "cloud" }}

apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-service
  labels:
    app: cloud-gateway
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: cloud-gateway

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway
  labels:
     app: cloud-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-gateway
  template:
    metadata:
      labels:
        app: cloud-gateway
    spec:
      securityContext:
        fsGroup: {{ $.Values.groupId }}
      enableServiceLinks: false
      containers:
        - name: cloud-gateway
          image: {{ $.Values.registryPrefix }}smtc_api_gateway{{ $.Values.releaseSuffix }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: {{ printf "http://%s-service:9200" (include "smtc.db.name" .) | quote }}
            - name: STHOST
              value: "http://cloud-storage-service:8080"
            - name: NO_PROXY
              value: "*"
            - name: no_proxy
              value: "*"
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
      volumes:
        - name: timezone
          hostPath:
            path: /etc/localtime
            type: File
      {{ include "smtc.platform.node-selector" . }}

{{- end }}
